name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Change directory and make
      run: cd STUN-server && make
  test:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: change directory and make test
      run: cd STUN-server && make test && ./TestProgram
