name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Change directory and make
      run: cd STUN-server && make
  test:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: change directory and make test
      run: cd STUN-server && make test && ./TestProgram

  deploy_STUN_server:
    name: deploy_STUN_server
    runs-on: ubuntu-latest
    steps:
    - name: testing STUNserver ssh connection
      uses: appleboy/ssh-action@master
      with: 
        host: 13.74.199.118
        username: azureuser
        key: ${{ secrets.STUN_SECRET }}
        port: 22
        script: | 
          cd P2P-app-with-STUN
          docker stop $(docker ps -a -q)
          docker rm $(docker ps -a -q)
          git pull origin main
          git status
          cd STUN-server
          docker-compose build stun-server
